# For loops in lists and dictionaries

### Problem 1

We are given an array of integers.

numbers = [8,5,9,2,4,0]

We also have a given target

target = 9

Please return the index of the target number using a for loop. The target number may repeat several times.

In [15]:
import numpy as np

In [16]:
numbers = [8,5,9,2,4,0]

In [17]:
target = 9

In [76]:
for num in numbers:
    if num == target:
        print(numbers.index(num))

2


In [18]:
len(numbers)

6

In [33]:
numbers_array = np.array([numbers])
print(numbers_array)

[[8 5 9 2 4 0]]


In [49]:
index_array = np.full([1,6], range(6))
print(index_array)

[[0 1 2 3 4 5]]


In [51]:
numbers_index_array = np.concatenate((numbers_array, index_array))
print(numbers_index_array)

[[8 5 9 2 4 0]
 [0 1 2 3 4 5]]


In [65]:
numbers_index_array[0]

array([8, 5, 9, 2, 4, 0])

In [75]:
for number in numbers_index_array[0]:
    if number == target:
        print(enumerate(number))


TypeError: 'numpy.int64' object is not iterable

Expected Output: 2


### Problem 2

What if we had multiple instances of the same target number in a given list numbers2? Could you print out the indexes of all the instances of 9?

In [77]:
numbers2 = [3,2,9,5,9,4,0,1,9]

In [78]:
for i, x in enumerate(numbers2):
    if x == 9:
        print(i)

2
4
8


Expected Output: 2,4,8

### Problem 3

Now I have a dictionary of key-value pairs that contain colors with a corresponding list of numbers.

In [79]:
my_dict = {
    'blue':[4,8],
    'red':[2,1],
    'black':[9,4],
    'green':[0,3],
    'orange':[6,8]
}

In [80]:
my_dict

{'blue': [4, 8],
 'red': [2, 1],
 'black': [9, 4],
 'green': [0, 3],
 'orange': [6, 8]}

{'blue': [4, 8],\
 'red': [2, 1],\
 'black': [9, 4],\
 'green': [0, 3],\
 'orange': [6, 8]}


How could I get rid of the entire key-value pair that contains our target number 9?

Expected Output: my_dict = {

'blue': [4, 8],

'red': [2, 1],

'green': [0, 3],

'orange': [6, 8]

}

In [81]:
for x in my_dict:
    if my_dict[x][0] == target:
        del my_dict[x]

RuntimeError: dictionary changed size during iteration

In [82]:
my_dict

{'blue': [4, 8], 'red': [2, 1], 'green': [0, 3], 'orange': [6, 8]}